### ISSUE TITLE
No KITTI formatted data is generated

### ISSUE THREAD

**Issue by SIGMIND** [NVIDIA-AI-IOT/face-mask-detection#2]
The data2kitti.py file not generating the KITTI formatted data in the output folder.

**Comment by Ziegan** [comment]
Whlie running the data2kitti.py by giving the required paths

I get output like this:


Total Mask Labelled:0 and No-Mask Labelled:0
Traceback (most recent call last):
  File "data2kitti.py", line 107, in <module>
    main()
  File "data2kitti.py", line 58, in main
    kitti_label = mafa2kitti(annotation_file=annotation_file, mafa_base_dir=mafa_base_dir,
UnboundLocalError: local variable 'annotation_file' referenced before assignment


Can anyone help me with this error?

**Comment by ak-nv** [comment]
May I know, what is the command you are running? Does it include ``--train``

**Comment by Ziegan** [comment]
Yes it includes --train 

the command i used is this:

python3 data2kitti.py   --kaggle-dataset-path /home/miniscale/workspace/tlt-experiments/face-mask-detection-data/Kaggle\ Medical\ Mask\ Dataset/ \
--mafa-dataset-path /home/miniscale/workspace/tlt-experiments/face-mask-detection-data/MAFA\ Dataset/ \ 
--fddb-dataset-path /home/miniscale/workspace/tlt-experiments/face-mask-detection-data/FDDB\ Dataset/ \ 
--widerface-dataset-path /home/miniscale/workspace/tlt-experiments/face-mask-detection-data/Wider\ Face\ Dataset/ \
--kitti-base-path /home/miniscale/workspace/tlt-experiments/data/training/label_2/ \
--train

**Comment by ak-nv** [comment]
Closing as no activity for 15 days. Please re-open if you see the same issue.
